apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: correlate
spec:
  version: v0.1.3
  homepage: https://github.com/Dasmat13/kubecorrelate
  shortDescription: Merge logs, events, and node pressures chronologically
  description: |
    KubeCorrelate is a lightweight CLI troubleshooting tool that multiplexes
    pod container logs, Kubernetes events, config updates, and node-level
    resource pressure alerts into a single time-aligned, colorized stream.
  caveats: |
    Requires an active kubeconfig context. Some features like Node watches
    might require permissions that fallback gracefully if missing.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/Dasmat13/kubecorrelate/releases/download/v0.1.3/kubecorrelate_0.1.3_darwin_amd64.tar.gz
    sha256: 1ef005a7839bd9bff9209f0c55ab910db16b6f2e3864566f5559b061c8e3b2fa
    bin: kubecorrelate
    files:
    - from: "kubecorrelate"
      to: "."
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/Dasmat13/kubecorrelate/releases/download/v0.1.3/kubecorrelate_0.1.3_darwin_arm64.tar.gz
    sha256: 7fd5330a36003823dfcceb7da4c0160401314b2dd8b248d05b54a638c31da1fa
    bin: kubecorrelate
    files:
    - from: "kubecorrelate"
      to: "."
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/Dasmat13/kubecorrelate/releases/download/v0.1.3/kubecorrelate_0.1.3_linux_amd64.tar.gz
    sha256: 683d77dbb1d467bd20a99e59f372c87b39c4b36e10b3183e85f91ab812d0f3e9
    bin: kubecorrelate
    files:
    - from: "kubecorrelate"
      to: "."
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/Dasmat13/kubecorrelate/releases/download/v0.1.3/kubecorrelate_0.1.3_linux_arm64.tar.gz
    sha256: 19e4f1dffc9a8b8fc8cd7dc27736d2347bfb3f41dd3526fedbdbb2415a9d6eb9
    bin: kubecorrelate
    files:
    - from: "kubecorrelate"
      to: "."
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/Dasmat13/kubecorrelate/releases/download/v0.1.3/kubecorrelate_0.1.3_windows_amd64.zip
    sha256: b1b5d7f9d9786c122a0a50c0191e7d31b7062716999490f23b66fbd152ba54fb
    bin: kubecorrelate.exe
    files:
    - from: "kubecorrelate.exe"
      to: "."
    - from: "LICENSE"
      to: "."
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    uri: https://github.com/Dasmat13/kubecorrelate/releases/download/v0.1.3/kubecorrelate_0.1.3_windows_arm64.zip
    sha256: 9856492664dfb1065af5bb05a500420796bacaba45ade0c0a2262d73ab113e62
    bin: kubecorrelate.exe
    files:
    - from: "kubecorrelate.exe"
      to: "."
    - from: "LICENSE"
      to: "."
